name: Deploy to Production

on:
  push:
    branches: [ main ] # Change to 'master' if your default branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Deployment Script on Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "/var/www/parakshtech-lms/deploy.sh"
